name: train-tracker-talk

options:
  bundleIdPrefix: com.twocentstudios.train-tracker-talk
  deploymentTarget:
    iOS: "18.0"
    macOS: "15.0"

configs:
  Debug: debug
  Release: release

fileGroups:
  - CLAUDE.md
  - SignificantChange/CLAUDE.md

packages:
  SharingGRDB:
    url: https://github.com/pointfreeco/sharing-grdb
    from: 0.1.0

targets:
  SignificantChange:
    type: application
    platform: iOS
    sources:
      - path: SignificantChange
        excludes:
          - "CLAUDE.md"
    dependencies:
      - package: SharingGRDB
    settings:
      DEVELOPMENT_TEAM: YK25EF78NT
      TARGETED_DEVICE_FAMILY: "1"
    info:
      path: SignificantChange/Info.plist
      properties:
        CFBundleDisplayName: 01 SigChange
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        LSRequiresIPhoneOS: true
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIBackgroundModes:
          - location
        NSLocationAlwaysAndWhenInUseUsageDescription: "Document signficant locations in the background"
        NSLocationWhenInUseUsageDescription: "Document signficant locations"